#!/bin/bash
# agents-collate.sh
#
# A Card Catalog for AI Agents
#
# Scans markdown headings and writes a heading-based table of contents into each AGENTS.md found from where you run it.
# Any AI agent reads the catalog, knows what exists, and drills into the full doc on demand.
#
# Scales to 1000s of docs with no context overhead and no special dbs.
# No vector DB, no embeddings, just this script.
#
# Usage: bash script/agents-collate.sh

set -euo pipefail

shopt -s globstar nocaseglob nullglob

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

_headings() {
  local md="$1" max_depth
  max_depth=$(awk '/^ *```/{in_code=!in_code;next}!in_code&&/^ *#/{sub(/^ */,"");match($0,/^#+/);if(RLENGTH>max)max=RLENGTH}END{print max+0}' "$md")
  echo "# $md"
  awk -v d="$max_depth" '/^ *```/{in_code=!in_code;next}!in_code&&/^ *#/{sub(/^ */,"");match($0,/^#+/);n=RLENGTH;sub(/^#+ */,"");if(n==d){print"- "$0}else{p="";for(i=0;i<=n;i++)p=p"#";print p" "$0}}' "$md"
  echo
}

cd "$REPO_ROOT"
for f in **/AGENTS.md; do
  (
    cd "$(dirname "$f")"
    printf '<!-- THIS FILE IS AUTOMATICALLY GENERATED DO NOT EDIT -->\n\n' > AGENTS.md
    for md in *.md; do
      [[ -f "$md" && "${md,,}" != "agents.md" ]] && _headings "$md" >> AGENTS.md
    done
    if [[ "$(pwd)" == "$REPO_ROOT" && -n "${AGENTS_INCLUDE_DIR:-}" && -d "${AGENTS_INCLUDE_DIR}" ]]; then
      for md in "$AGENTS_INCLUDE_DIR"/*.md; do
        [[ -f "$md" ]] && _headings "$md" >> AGENTS.md
      done
    fi
  )
done
