#!/bin/bash
set -eo pipefail

export CLINE_OTEL_TELEMETRY_ENABLED=false

if [[ -n "${OPENROUTER_API_KEY:-}" ]]; then
  npm i -g cline
  cline auth -p "openrouter" -k "$OPENROUTER_API_KEY" -m "~anthropic/claude-sonnet-latest" --reasoning-effort "high"
fi
