#!/bin/bash
set -euo pipefail

bindir="$HOME/.local/bin"
mkdir -p "$bindir"

os="$(uname -s | tr '[:upper:]' '[:lower:]')"
arch="$(uname -m)"
case "$os" in linux*) os=linux ;; darwin*) os=darwin ;; mingw*|msys*|cygwin*) os=windows ;; esac
case "$arch" in x86_64|amd64) arch=amd64 ;; arm64|aarch64) arch=arm64 ;; esac

bin="$bindir/yq"
url="https://github.com/mikefarah/yq/releases/latest/download/yq_${os}_${arch}"
[[ "$os" == 'windows' ]] && { bin="$bindir/yq.exe"; url="${url}.exe"; }

wget -qO "$bin" "$url"
chmod +x "$bin"
