#!/bin/bash
set -eo pipefail

if [[ -n "${KILO_CODE_ENABLE:-}" ]]; then
  npm install -g @kilocode/cli
  mkdir -p "$HOME/.config/kilo"
  cat > "$HOME/.config/kilo/opencode.json" <<EOF
{
  "$schema": "https://app.kilo.ai/config.json",
  "provider": {
    "openrouter": {
      "options": {
        "apiKey": "$OPENROUTER_API_KEY"
      },
      "models": {
        "claude-sonnet-latest": {
          "id": "~anthropic/claude-sonnet-latest"
        },
        "claude-haiku-latest": {
          "id": "~anthropic/claude-haiku-latest"
        }
      }
    }
  },
  "model": "openrouter/claude-sonnet-latest",
  "small_model": "openrouter/claude-haiku-latest"
}
EOF
fi
