#!/bin/bash
# Prepare Git
## Configure git for agent repos
### Stage protocol files
#### Build the agent index
### Strip the agent index

set -euo pipefail
shopt -s globstar nocaseglob nullglob dotglob

REPO_ROOT="$(git rev-parse --show-toplevel)"
SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
DOTFILES_ROOT="$(cd "$(dirname "$SCRIPT_PATH")/.." && pwd)"
MODE="${1:-hydrate}"

cd "$REPO_ROOT"

if [[ -f AGENTS.md ]]; then
  grep -qsF 'AGENTS.md filter=agents' .git/info/attributes \
    || echo 'AGENTS.md filter=agents' >> .git/info/attributes
  grep -qsF '*_PROTOCOL.md' .git/info/exclude \
    || echo '*_PROTOCOL.md' >> .git/info/exclude
  git config filter.agents.clean 'echo "<!-- DO NOT EDIT THIS FILE IS AUTOMATICALLY GENERATED -->"'
  git config filter.agents.smudge cat
else
  rm -f ./*_PROTOCOL.md
fi

if [[ "$MODE" == 'dehydrate' ]]; then
  for f in **/AGENTS.md; do
    [[ -L "$f" ]] && continue
    echo '<!-- DO NOT EDIT THIS FILE IS AUTOMATICALLY GENERATED -->' > "$f"
  done
elif [[ -f AGENTS.md ]]; then
  PROJECT_PROTOCOLS=("$DOTFILES_ROOT"/protocols/*/PROTOCOL.md)
  DOTFILES_PERSISTED_DIR="$(cd "$DOTFILES_ROOT/.." && pwd)/dotfiles"
  DOTFILES_PROTOCOLS=("$DOTFILES_PERSISTED_DIR"/protocols/*/PROTOCOL.md)
  for proto in "${PROJECT_PROTOCOLS[@]}" "${DOTFILES_PROTOCOLS[@]}"; do
    [[ -f "$proto" ]] || continue
    name="$(basename "$(dirname "$proto")")"
    if [[ "$proto" == *"$DOTFILES_PERSISTED_DIR"* ]]; then
      prefix='DOT_'
    else
      prefix=''
    fi
    cp "$proto" "$REPO_ROOT/${prefix}${name^^}_PROTOCOL.md"
  done

  for f in **/AGENTS.md; do
    [[ -L "$f" ]] && continue
    (
      cd "$(dirname "$f")"
      echo '<!-- DO NOT EDIT THIS FILE IS AUTOMATICALLY GENERATED -->' > AGENTS.md
      for md in *.md; do
        [[ -f "$md" && ! -L "$md" && "${md,,}" != 'agents.md' ]] || continue
        max_depth="$(awk '
          /^ *```/ { in_code = !in_code; next }
          !in_code && /^ *#/ {
            sub(/^ */, "")
            match($0, /^#+/)
            if (RLENGTH > max) max = RLENGTH
          }
          END { print max+0 }
        ' "$md")"
        {
          echo
          title="$(printf '%s' "${md%.md}" | tr -cs 'a-zA-Z' ' ')"
          echo "# $title"
          awk -v max_depth="$max_depth" '
            /^ *```/ { in_code = !in_code; next }
            !in_code && /^ *#/ {
              sub(/^ */, "")
              match($0, /^#+/)
              n = RLENGTH
              sub(/^#+ */, "")
              if (n == max_depth) {
                print "- " $0
              } else {
                prefix = ""
                for (i = 0; i <= n; i++) prefix = prefix "#"
                print prefix " " $0
              }
            }
          ' "$md"
        } >> AGENTS.md
      done
    )
  done
fi
