#!/bin/bash
set -euo pipefail
DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"

source "$DIR/bootstrap"
source "$DIR/dehydrate-agents"
source "$DIR/push-git"
source "$DIR/teardown"
