#!/bin/bash
set -euo pipefail
DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"

source "$DIR/unwire-shell"
source "$DIR/unwrite-dotfilesrc"
source "$DIR/unconfigure-git"
source "$DIR/unconfigure-python"
source "$DIR/unstage-rules"
source "$DIR/unlink-skills"
