#!/bin/bash
# agents-collate.sh 
#
# A Card Catalog for AI Agents
#
# Scans markdown headings and writes an indented table of contents into each AGENTS.md found from where you run it.
# Any AI agent reads the catalog, knows what exists, and drills into the full doc on demand.
#
# Scales to 1000s of docs with no context overhead and no special dbs.
# No vector DB, no embeddings, just this script.
#
# Usage: bash scripts/agents-collate.sh

set -euo pipefail

shopt -s globstar nocaseglob nullglob

for f in **/AGENTS.md; do
  (
    cd "$(dirname "$f")"

    output='<!-- THIS FILE IS AUTOMATICALLY GENERATED DO NOT EDIT -->

'

    for md in *.md; do
      if [ -f "$md" ] && [ "${md,,}" != "agents.md" ]; then
        output+="${md}:"$'\n'
        output+="$(awk '
          /^ *```/ { in_code = !in_code; next }
          !in_code && /^ *#/ {
            sub(/^ */, "")
            match($0, /^#+/)
            n = RLENGTH
            sub(/^#+ */, "")
            printf "%*s", (n-1)*2, ""
            print "- " $0
          }
        ' "$md")"$'\n'
        output+=$'\n'
      fi
    done

    printf '%s' "$output" > AGENTS.md
  )
done
