name: Update Generated Files

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: bash script/bootstrap.sh
      - run: bash script/prepare-git.sh dehydrate
      - run: bash script/push-commit.sh
