name: Update Generated Files

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

env:
  GITHUB_PATH: script

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Hydrate Agents
        run: hydrate-agents
      - name: Update Contents
        run: update-contents
      - name: Update Manifest
        run: update-manifest
      - name: Setup Dev
        run: setup-dev
      - name: Dehydrate Agents
        run: dehydrate-agents
      - name: Commit changes
        run: commit-changes
