name: Update Generated Files

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Hydrate Agents
        run: ./script/hydrate-agents
      - name: Update Contents
        run: ./script/update-contents
      - name: Update Manifest
        run: ./script/update-manifest
      - name: Setup Dev
        run: ./script/setup-dev
      - name: Dehydrate Agents
        run: ./script/dehydrate-agents
      - name: Commit changes
        run: ./script/commit-changes
